### ISSUE TITLE
Customize which items are displayed/hidden from the home menu

### ISSUE THREAD

**Issue by kaaholst** [kaaholst/android-squeezer#637]
Copied from a Google Play review:

Fast in connection but not very configurable and full of unnecessary categories. Can't customize the main menus with what you want? Extra, my app, gallery .. Can they be removed? Same thing inside MY MUSIC: can only the desired categories be displayed?

Original issue reported on github.com/nikclayton/android-squeezer by kaaholst on 2020-04-15T18:10:10Z

**Comment by kaaholst** [comment]
Totally agree, this feature would be great!

Original issue reported on github.com/nikclayton/android-squeezer by Jorgeno on 2020-12-17T18:08:22Z

**Comment by anjoku** [comment]
I agree too, this feature would be great!

**Comment by kaaholst** [comment]
This is available with the Archive function. Closing this.
