### ISSUE TITLE
Automatic connection on app startup

### ISSUE THREAD

**Issue by kaaholst** [kaaholst/android-squeezer#640]
Hi all!
Thanks so much for creating squeeze, I love it and I use it a lot! 

There is just a small issue: if I open the app it almost asks me each time what server I want to connect to. I confirm the preselected (only) server and it connects. 

I only have one server in my network, I don't use my squeezebox.com and left it blank in the settings. 

Is this a small bug or is there a workaround so that the app won't ask on startup?

Thanks and keep up the excellent work!

BeeJayF

Original issue reported on github.com/nikclayton/android-squeezer by beejayf on 2020-05-16T09:11:09Z

**Comment by kaaholst** [comment]
I observe the same behavior. I suppose it can be due to the energy saving policy, where either the application or the WiFi connection is being put into sleep. Still it would be nice if squeezer connected to the latest selected server automatically in this case as it does while being manually started.

Original issue reported on github.com/nikclayton/android-squeezer by eremem on 2020-05-18T10:20:24Z

**Comment by kaaholst** [comment]
Hi,  Yes I'd also agree with this.  On android 10 (Xiaomi Mi A2 Lite), I'm often, but not always, presented with the connection screen on app start or restart, which just requires the hitting the 'CONNECT' button as all the other settings are good to go.  I'm not sure if the 1st attempt at automatic connection times out or something, but perhaps the app could try more than once to connect automatically?, 

Original issue reported on github.com/nikclayton/android-squeezer by diyfiddler on 2020-07-17T07:00:53Z

**Comment by kaaholst** [comment]
Same here in Android V10. 

Original issue reported on github.com/nikclayton/android-squeezer by dbu828 on 2020-07-25T09:39:50Z

**Comment by kaaholst** [comment]
Version 2.2.0 connects automatically unless it's disconnected manually (via the disconnect from the 3-dot options menu in the top right corner).
I thinks some of the disconnects is caused by Android closing either network or the Squeezer service, depending on Android version and device model, so I'm afraid I can't do anything about that.
Thanks for the feedback

Original issue reported on github.com/nikclayton/android-squeezer by kaaholst on 2020-09-17T21:39:05Z

**Comment by eremem** [comment]
There seems to be a regression introduced in the current version (2.2.4).

After updating to it on my 2 different devices (Android 10 & 11), the application, after bringing it to the foreground, recognizes the lost connection, looks for the server, finds it and... doesn't reconnect. This doesn't occur every time but still quite regularly. Previously it worked every time as expected.

Now if it happens, you still can reconnect manually by pressing the button. The LMS works OK, the network too, all my clients play the music w/o any problems all the time.
