### ISSUE TITLE
all Spotify albums are marking with a Spotify logo ?

### ISSUE THREAD

**Issue by anjoku** [kaaholst/android-squeezer#679]
Hi,

I think Squeezer is very good and I could also imagine donating something.

But what bothers me a lot and makes it almost useless for me is the lack of labeling of Spotify titles.
In the LMS web interface, all Spotify albums are marked with a Spotify logo.

Is it possible to mark this in Squeezer too?

Best regards

Andre
![image](https://user-images.githubusercontent.com/72342904/110129041-c1e66d80-7dc7-11eb-8645-22f26d2dca78.png)

**Comment by kaaholst** [comment]
I don't know how that feature works on the web-interface, but it certainly seems like something we should have in Squeezer, so I'll look into it and see what I can do.

Thanks for the feedback.

**Comment by anjoku** [comment]
Hi,

thanks, that would be great.

**Comment by SamInPgh** [comment]
...and Qobuz too. I now have both Tidal and Qobuz, and the library view in Squeezer is quite confusing without the logo. Here is a screenshot from another LMS client that shows the logos:

![Screenshot_2021-11-05-15-10-25](https://user-images.githubusercontent.com/78810692/140565693-83de7b0a-6b8d-451b-831c-6557d1a22d85.jpg)

Is there any progress on this request?

**Comment by kaaholst** [comment]
I'm afraid no, there is no progress on this one. I checked the server code, and it appears that the feature has been implemented in a way, that it's not possible to get the information using the cometd protocol. I will create an issue on the slim forum or alternatively on the LMS github repository.

**Comment by SamInPgh** [comment]
Ok, Kurt. Thanks for the update. Just curious though. How does the other client app get the logo info? I assume they are using a different method/protocol for communicating with LMS?

**Comment by kaaholst** [comment]
I created an issue in the [slim forum](https://forums.slimdevices.com/showthread.php?115432-How-to-get-extid-in-e-g-the-albums-list-using-the-SqueezePlay-interface).

I think that explains how I think they get the information. They use the album, artist and titles queries.

**Comment by kaaholst** [comment]
Please try this [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing). Items from a music service are marked with the corresponding logo.

After test, you may continue to use this apk, it will automatically be updated when an new version is released. You can also revert to the version on Google Play, if you prefer to use an official version.

**Comment by SamInPgh** [comment]
It doesn't work for me with Qobuz. I am no longer using Tidal or Spotify so I can't comment on them. The Qobuz logo is displayed correctly on both the LMS web and Squeeze Ctrl clients.

**Comment by kaaholst** [comment]
Oh, I forgot, this requires LMS 8.3, so it can't be tested yet. See the linked issue in slim-forum.

**Comment by SamInPgh** [comment]
I just installed the latest LMS 8.3 nightly build and the Qobuz logo is now displayed correctly. Thanks!

**Comment by kaaholst** [comment]
This is available from version 2.2.8 which is now on Google Play.

Note that it requires LMS 8.3 or later.

Closing this
