### ISSUE TITLE
Contributing notes outdated for AS 4.1.3 on Ubuntu 20.04

### ISSUE THREAD

**Issue by bvrulez** [kaaholst/android-squeezer#681]
I am sorry to bother you with basics. I tried to import the project using your notes (https://github.com/kaaholst/android-squeezer/blob/develop/CONTRIBUTING.md).

> In the "Select File or Directory to Import" dialog that appears, navigate to the directory that you fetched the Squeezer source code in to and select the build.gradle file that ships with Squeezer.

I get an error "This file already exists." 

I suppose it is sufficient to chose the directory. I can import that.

> In the "Import Project from Gradle" dialog tick "Use auto-import" and make sure that "Use gradle wrapper (recommended)" is selected.

There is no such dialog when I import the directory.

> Copy ide/intellij/codestyles/AndroidStyle.xml to Android Studio's config directory.

    Linux: ~/.AndroidStudioPreview/config/codestyles

I can not find this directory. I have `~/.android` but no folder `config` in it. I installed with `snap install android-studio --classic
` in Ubuntu 20.04.

After importing I get an error on build: sync: `Task 'wrapper' not found in project ':Squeezer'.`

EDIT: I think I might be missing the gradle wrapper since it is a totally fresh install of AS and I have not other projects.

**Comment by bvrulez** [comment]
I did this on Linux inside a Virtualbox virtual machine. The machine lacked some hardware support. Importing the project on the Windows host worked just fine.

**Comment by kaaholst** [comment]
Thanks for the update, and I'm happy you got it working. I just tried to make a fresh clone, and import using build.gradle from  the root folder. 

You are right that the instructions are outdated. There is no import dialog. Also you do not need the AndroidStyle.xml file. Just use the IDE default settings and try to follow the existing style in any file you change. Do NOT reformat the whole file. 

I will update the instructions.

**Comment by bvrulez** [comment]
Thank you for this awesome app. I also sent you an email some hours ago. Have a nice weekend!
