### ISSUE TITLE
Feature Request: Support for muting/unmuting via the client "mixer muting" command

### ISSUE THREAD

**Issue by SamInPgh** [kaaholst/android-squeezer#684]
I would like you to consider adding support for player muting in Squeezer in the following ways:

1. Offer the alternative of muting the player (via "mixer muting") instead of pausing ("pause") when a phone call is made or received. (I believe that Orange Squeeze does this.)

2. Add a "Mute/Unmute" toggle button to the Squeezer volume screen, again using the "mixer muting" command.

This feature would be useful to me as one of the developers working on the Denon AVP/AVR Control LMS plugin.

Thanks.

**Comment by kaaholst** [comment]
Hi Sam,

I think support for the "mixer muting" command should be fairly straight forward to implement, so I will definitely consider it for the next Squeezer release.

Thanks for the suggestion.

**Comment by SamInPgh** [comment]
Thanks for considering the request, Kurt. Here is a little background information for when you start working on it:

Since users of the Denon AVP/AVR Control plugin, and others like it, generally have a high level of interest in preserving the purest possible digital signal from their players to the AV receiver (or other outboard processor), the vast majority of them (including myself) use the LMS "Player->Audio->Volume control" setting of "Output level is fixed at 100%", as well as no cross-fading or volume adjustment/replay gain. We rely, however, on seeing the "mixer volume" commands being sent to the player so that we can translate them into volume control commands for the AV receiver and, on occasion, query the player for its current volume setting in order to stay in sync. The client app developers understand this and send the volume changes to the player regardless of whether it is configured for "fixed at 100%" or not.  I have found, however, at least two client apps that, although they have limited support for the "mixer muting" command, seem to think that they should not send it to a player whose output level is "fixed at 100%" (I believe the player attribute is called 'digitalVolumeControl' but I'm not positive). I'm not sure why this is the case. One reason could be that they don't want to deal with customers complaining that the muting function "doesn't work" on their system as the player itself will not mute, just as it does not change its output level on volume changes. Or maybe they have been asked by developers of other plugins to implement this behavior, possibly because they didn't want to have to program for the volume maintained by the player going negative as a result of the mute request (it does). I don't know. If you have any insight into this from a client developer's viewpoint, I would appreciate hearing it. The bottom line is that my request explicitly includes NOT withholding the "mixer muting" command based on this criterion. We need to see it so that we can issue the "mute/unmute" requests to the AVR. As an interim measure, I have implemented a hardware "mute" function in the next version of the plugin which looks for a volume up "mixer volume +n" and a volume down "mixer volume -n" arriving within .25 seconds of each other and treating this condition as a "mute" command. It works very nicely with Squeezer by simply pressing both hardware volume buttons simultaneously. However, it would be nice to have true support for the player mute function on the volume screen and also as an option for use during phone calls.

Anyway, thanks for a great (and free!) app. I look forward to working with you on this enhancement.

-Sam

**Comment by kaaholst** [comment]
Hi,

I have created a version with support for the "mixer muting" command.

Generally it's working OK, except I have some players connected via the Chromecast bridge plugin. Here the player is not muted/unmuted.
Do you have any experience with that?

About the fixed volume setting, it's correct that Squeezer ignores the "digitalVolumeControl" flag. The reason for that is simply, that I have never gotten around to implement it!
I understand from your message that this is the correct behaviour?

I don't know if it matters but for hardware volume buttons Squeezer sends  relative volume changes as in "mixer volume +5"  
for the volume controllers in the volume pop-up and in the players screen we send the volume as in "mixer volume 75"

I found the "getexternalvolumeinfo" command which potentially could be used to control this behaviour. However it doesn't return anything on my system.

**Comment by SamInPgh** [comment]
Hi Kurt! I'm glad to hear you're working on this. Yes, I use Philippe's CastBridge plugin to control two Chromecast devices and a Google Nest Mini stereo pair. The mixer mute function did not work correctly with those devices until Philippe fixed a bug in LMS that I recently pointed out to him. That fix is included in LMS 8.1.2 starting with the April 9 build so check that you are running the latest version.

Regarding how you are currently handling volume requests, everything looks fine there as far as I am concerned. I wouldn't worry about checking the digitalVolumeControl flag unless the need comes up for some other reason. The only comment I have regarding volume control is that other client apps such as SqueezeCtrl and XSqueezeIt (the new kid on the block) use a preference setting to control the up/down increment for the "mixer volume +/-" volume changes. I feel that 5 is a good choice for a fixed amount though.

I'm anxious to see how you have implemented the mute function in Squeezer. If you want to send me the APK, I would be happy to test it out with my plugin and give you some feedback.

Thanks and regards,

-Sam

**Comment by SamInPgh** [comment]
One correction to my previous post: Philippe's LMS fix that corrected the mute problem with Chromecast players was rolled into LMS 8.1.2 beginning with the April 16 build -- not April 9.

**Comment by kaaholst** [comment]
Please try this [apk](https://drive.google.com/file/d/1siDK51RVJPK7AeIHfEVkkbgGC-U24bMq/view?usp=sharing). To install it open the link on your phone.

Currently it's not possible to select mute on incoming calls. I will implement this next, and while at it maybe also add a preference for the step for the hardware buttons.

**Comment by SamInPgh** [comment]
Thanks, Kurt. It works great. Looking forward to the other enhancements you
have planned.

**Comment by SamInPgh** [comment]
Ah, yes... I can see the how that might be problematic. I'm not convinced
of the usefulness of doing it anyway. The important part is the
muting/pausing, which is a feature that I find very handy.

**Comment by kaaholst** [comment]
This is implemented in Squeezer version 2.2.5, so closing this.

Thank you!
