### ISSUE TITLE
Feature Request: Add Alpha UI on Album/Artists Lists Panels

### ISSUE THREAD

**Issue by aesculus** [kaaholst/android-squeezer#687]
It would really help if there was an alpha list on the side of the album and artists lists.

This way the user would not have to scroll through potentially hundreds of items to go to an item many panels away. Ie touch the M to go directly to the top of the Ms in the listing.

**Comment by kaaholst** [comment]
There's already an issue for this request #83.

Please comment on that issue instead. I'm closing this as a duplicate.

Thank you!

**Comment by aesculus** [comment]
My own search skills seem to be remiss. :-(
