### ISSUE TITLE
Double entries for all menu items until app restart

### ISSUE THREAD

**Issue by lankygit** [kaaholst/android-squeezer#688]
![Screenshot_20210331-054248](https://user-images.githubusercontent.com/5887569/113092539-1540b580-91e6-11eb-80ce-48f13a83b191.jpg)
![Screenshot_20210331-054253](https://user-images.githubusercontent.com/5887569/113092542-170a7900-91e6-11eb-9973-d410e6828c1d.jpg)

This is the first and only time this has happened. I use the app a few times per day. Browsed around and it didn't clear. Killed app and restarted: all back ok.

2.2.4-beta-1

**Comment by kaaholst** [comment]
That's a bug, thanks for the feedback. Apparently there is a race condition in the fetch of the players home menu from LMS. I will try to fix that.

You may also disconnect and reconnect to clear the problem, if you prefer.

**Comment by kaaholst** [comment]
A new beta version is released which fixes this issue.

**Comment by kaaholst** [comment]
Version 2.2.4 with as fix for this issue is released, so closing this.

Thanks for the help sorting this out,
