### ISSUE TITLE
Playback is stopped by "ghost" (spam) calls

### ISSUE THREAD

**Issue by climategadgets** [kaaholst/android-squeezer#693]
The "Pause music on call" feature stops the playback when it shouldn't.

* Expected behavior: playback is paused when a call visible to the user is received.
* Actual behavior: playback is paused even when the incoming call is filtered as spam by Android and is only visible as "spam call" or "missed call" (the phone never rings). The perceived behavior is that Squeezer stops the music for no reason at all.

It is unclear if this is only happening with incoming calls redirected to the phone by Google Voice, or with all incoming calls.

**Comment by kaaholst** [comment]
I'm afraid the API I'm using is only notifying me on these options:
TelephonyManager.CALL_STATE_IDLE, TelephonyManager.CALL_STATE_RINGING, or TelephonyManager.CALL_STATE_OFFHOOK.

When call state changes to something different from CALL_STATE_IDLE, Squeezer stops the music.

There is an alternative API AudioManager, which among other things also supports VOIP Call such as Skype and Facebook messager. But Squezer does not play music on it's own, it is a remote control for LMS, so we don't own the audio on the phone.so I don't think we can use that.

I'm afraid your only options are to disable this feature in Squeezer (3-dot menu in the top bar, and then settings) or live with the music pausing on on "ghost" calls.

**Comment by climategadgets** [comment]
Looks like there's a filter somewhere between `TelephonyManager.CALL_STATE_RINGING` and the UI which never gets it.
Well, Android is evolving, so maybe they do something about that in the future. Feel free to close this for now.

**Comment by kaaholst** [comment]
Ok, closing this.
Thanks anyway for the feedback.
