### ISSUE TITLE
Failed setting up new Alarm Clock/ Possible Bug

### ISSUE THREAD

**Issue by Legitwarrior** [kaaholst/android-squeezer#694]
Hi there,
thanks for the great app. 
Since last update on android 2.2.4, when I add a new alarm to Squeezebox Touch or Radio, I can't enter the time correctly. For example, when I enter 9:00 it sets a time of 00:09. So it seems that I can't add the correct hour. I tried it on two different android devices and two squeezeboxes.

**Comment by kaaholst** [comment]
I just to tried to add an alarm, and it seems to work, see the screenshots below.
Please elaborate the steps you perform to have the hour entered erroneously.

![image](https://user-images.githubusercontent.com/428304/115973440-44341800-a555-11eb-96cf-d68cfe678e5e.png)
![image](https://user-images.githubusercontent.com/428304/115973485-9412df00-a555-11eb-80ae-c88cd72f6c67.png)
![image](https://user-images.githubusercontent.com/428304/115973511-d63c2080-a555-11eb-8397-5941bfa5fadc.png)
![image](https://user-images.githubusercontent.com/428304/115973793-01277400-a558-11eb-9d5a-f1677fe3d74b.png)

**Comment by kaaholst** [comment]
I think I found it. If the alarm clock is set via Settings/Alarm Clock, then it will be wrong.

This is fixed in the next release, thanks for the pointing this out.

In the mean time, you can set the alarm time via the 3-dot menu on the top right, and then Alarm Clock.

**Comment by Legitwarrior** [comment]
Thanks for your answer. Looking forward to the fix.

**Comment by kaaholst** [comment]
This is fixed in Squeezer version 2.2.5, so closing this.

Thank you!
