### ISSUE TITLE
Missing Music & Artist Information via Squeezer

### ISSUE THREAD

**Issue by MicPra** [kaaholst/android-squeezer#696]
Artist/ Album information regarding e.g. pictures/ album cover online are missing. But on my system it's only via Squeezer. Web UI like Material works fine.
The MAI Developer/M. Herger assumes it's the way how it's calling MAI.

See: https://forums.slimdevices.com/showthread.php?99537-Announce-Music-amp-Artist-Information-plugin/page159

**Comment by kaaholst** [comment]
I found out why pictures/ album cover online are missing, and a possible fix for it. Check out the updates on the thread above.

**Comment by MicPra** [comment]
I've followed the thread in the slimdevice forum... 😁. That are great news...  thanks a lot for it!

**Comment by kaaholst** [comment]
This is implemented in Squeezer version 2.2.5, so closing this.

Thank you!

**Comment by MicPra** [comment]
I can confirm - it's working
