### ISSUE TITLE
Time counter while live streaming

### ISSUE THREAD

**Issue by MicPra** [kaaholst/android-squeezer#698]
I'm not sure if there was... but I guess there was a timer while playing live streams. Now it's just 0 behind and before the progress bar. A simple counter showing the time the stream played already would be nice.

**Comment by kaaholst** [comment]
You are right we had that in an earlier version. 
The next version will show the information we get from LMS in the now playing screen. For live streams this will be a counter before the progress bar and 0 for duration (after the progress bar). The progress bar is disabled when duration is zero.

**Comment by MicPra** [comment]
perfect - when do you plan the next release?

**Comment by kaaholst** [comment]
This is now available in a [beta](https://play.google.com/apps/testing/uk.org.ngo.squeezer) version, or you can wait for the official release.

**Comment by kaaholst** [comment]
This is fixed in 2.2.7 so closing this.

Thank you!
