### ISSUE TITLE
Feature Request: Keep Group Players Volume Offset

### ISSUE THREAD

**Issue by H34dl3ss** [kaaholst/android-squeezer#699]
It's very nice to have the possibility to group players and control the volume simultaneusly via the sync option BUT,
unfortunately not all devices contribute with the same absolute loudness.
e.g. I have to set some players to 75% of their max. loudness to be able to notice them while the others are playiing at 50%.
The idea is to have the existing volume offset locked when enabling volume sync.

If the explanation is not sufficient, please ask and I will try to explain better.

**Comment by kaaholst** [comment]
Currently Squeezer has two ways of synchronizing the volumes for players in a player group.

If you select to synchronize the volumes via the 3-dot menu to the right of of a player group, Squeezer will set an option in LMS to have the volumes synchronized. In this mode the volume will be the same for all players in the group. This is actually done by LMS, and you can also set this option via the LMS web interface.

If you don't choose to synchronize the player volumes (force the volumes to be identical), Squeezer will display a volume bar for the player group. You can then set the individual volume for each player, and when you are happy with the offsets, you can adjust the volume using the bar for the group, which will keep the offsets.

![5-player-control](https://user-images.githubusercontent.com/428304/117360611-4b461900-aeb9-11eb-9a33-affa02c5cf54.png)

**Comment by kaaholst** [comment]
I hope this explanation is working for you.

I'm closing this issue, if you have any further comments/questions, feel free to reopen.

Thank you!

**Comment by H34dl3ss** [comment]
Hi, I tried this and it works of course.
Thanks so far!

There is one usability issue though.
The control via volume buttons on the smartphone are always assigned to a certain player.
Can we have the buttons set up to control the group?
If not, you have to go to the players options each time to control the volume of the group - not very comfortable.

**Comment by kaaholst** [comment]
You are quite right this is an issue. I think this is the same with the volume popup

I'll reopen this issue, and give it a try, to see if I can make it work.

**Comment by kaaholst** [comment]
You can try this [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing)

I changed so now volume buttons and the volume popup controls the group. If you want to set the volume of the individual players in a group, you have to go to the players screen.

I hope this helps!

**Comment by H34dl3ss** [comment]
Finally managed to play with the squeezer setup again. Not sure if I missed a setting or what, but I can't get it to work. I still can't control the group. Is it correct that this internal version is 2.2.7 (104)?

**Comment by kaaholst** [comment]
The most visible verification of this functionality is to select a synced player and bring up the volume popup. The popup shall show the names of all the players in the group.

![image](https://user-images.githubusercontent.com/428304/133927436-b5cad0c4-9298-4d0c-9a4d-97722522f17d.png)

The player needs to be synced but volume must not be synced, in which case volume will be the same for all players in the sync group (this is managed by LMS).

Another way to verify this change is to select a select a synced player, bring up the players screen and scroll to the sync group of the selected player. If you then use the hardware volume buttons, you should see the volume change of all the players in the sync group, while keeping the volume offsets.

**Comment by H34dl3ss** [comment]
I uninstalled the app and reinstalled this internal version just to rule that out and still don't see the screen as you have it. Please tell me how I can help to trouble shoot.

**Comment by kaaholst** [comment]
I'm not able to tell why it's not working for you. To rule out it's the wrong version, I updated the internal version (link is the same), and gave it a specific version number: "2.2.7-beta-10".

Please confirm that you can install this version.

When that's in place, please update this issue with what you experience, and what you expect. To make sure we're on the same page.

**Comment by H34dl3ss** [comment]
Great job! The recent version (beta 10) works. Thanks for implementing this feature!

**Comment by kaaholst** [comment]
Thanks for the feedback, I'll close this issue.

You can keep this version if you like, it is, like I said, just a snapshot of the development branch. It will be automatically updated when the next version is released, which will include this feature.

If you prefer an official version, you can uninstall the internal version, and install Squeezer from Google Play or f-droid.

Thank you!
