### ISSUE TITLE
Adding track while paused deletes existing playlist

### ISSUE THREAD

**Issue by H34dl3ss** [kaaholst/android-squeezer#700]
I'm not sure if this is intended or a bug - hope it's the latter.
Just dumped my playlist twice like this. It's not an expected behavior!
I expected the pop-up to appear that is usually happening when selecting a track.

There is an option to "ask before deleting current playlist".
Although ticked, the playlist is deleted without question.

**Comment by kaaholst** [comment]
You can control this behaviour via the player setting: Defeat destructive Touch-To-Play.
Select players from the 3-dot menu on the top right then select Defeat destructive Touch-To-Play from the 3-dot menu to the right of the player you wish to configure.

The "Ask for confirmation before clear current playlist" option is for the delete button in the current playlist  screen.
How can I  make this more clear?

**Comment by bvrulez** [comment]
To try to answer the question: "Defeat destructive Touch-To-Play" seems to be a rather generic term. Maybe this could be better.

**Comment by H34dl3ss** [comment]
@kaaholst 
Thanks for the pointer! That is exactly what I was looking for!
The setting is quite hidden though.
