### ISSUE TITLE
Application fails to connect to the server (as of 2.2.4)

### ISSUE THREAD

**Issue by climategadgets** [kaaholst/android-squeezer#703]
### Expected Behavior
On startup, the application connects to the server seamlessly, having restored the context, and proceeds as usual.
### Actual Behavior
* The application fails to connect at all. Pressing the "Connect" button causes the "Connecting" box to pop up and a delay, after which the control is returned to the "Connect" screen.
* This behavior is observed majority of the time (>80% would be a fair estimate). Sometimes, the application simply connects to the server with a barely noticeable delay and proceeds as expected. There is no clear correlation of connect/no connect behavior to any observable factors.
* This behavior is observed on 3 phones with different Android versions.
* This behavior is observed on the network where previous Squeezer versions worked without a hitch, and the configuration of which hasn't changed for a long time.

**Comment by kaaholst** [comment]
On some networks/servers we experience disconnects for reasons I have not been able to discover.

Recent Squeezer versions attempt to circumvent this by an automatic reconnect when a disconnect occurs.

Does this also happen with latest Squeezer version 2.2.7?

**Comment by climategadgets** [comment]
Yes, it does. This never happened with earlier versions - Squeezer always connected on the first try in less than a second. It's been used since its very early days, track record was spotless as far as connecting to the server goes - nor did the server or network setup change.

**Comment by kaaholst** [comment]
OK, thanks for the quick reply.

I have a few questions, to help pinpoint this issue.

1. I understand this issue started with version 2.2.4. Is that correct?
2. Do you have any phone on which Squeezer works as expected?
2. What is the IP-address of the server as reported after a server-scan in the Squeezer connect-screen?
3. What is the IP-address of the android phone? (just one example is enough)
4. If you haven't tried this already, please try to uninstall/reinstall Squeezer on one of the failing phones.
5. When/if this happens I'm interested in the server logs leading up to the disconnect. In the LMS web-interface select Settings/Advanced/Logging and raise the "(network.cometd) - Cometd protocol logging" log-level to Debug.
Check the log-messages for any sensitive information, and then attach them to this issue.

**Comment by born-daniel** [comment]
I don't know if it's the same issue but most of the time it connects seamlessly but other times it just sits there with the progress bar spinning. If I quickly exit and re-enter, it will be connected with no delay. It seems to be happening more frequently now. 
Samsung S10e, android 12, squeezer v2.2.9

**Comment by kaaholst** [comment]
@born-daniel I think you are experiencing a different issue. After Squeezer successfully connects to LMS, it fetches the home menu for the active player. While waiting for the home menu, the progress bar is shown. Sometimes when the response arrives, the display is not updated. The easiest way to display the home menu, is to bring up the Now Playing screen and bring it back down again.

**Comment by kaaholst** [comment]
I managed to reproduce this behaviour using a setup involving access via mobile network and VPN. Being able to reproduce I was then able to make fix for the issue. It's a general reliability fix for communication between Squeezer and LMS, so it may fix your setup also.

Please try this [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing).

When you are done testing, you may continue to use this apk, it will automatically be updated when an new version is released.

**Comment by born-daniel** [comment]
Thanks, I will try it.
One thing I noticed the last time it happened, I switched players while it was in a loop and it worked right away (same LMS obviously).
I will report if/when the problem happens again while using the apk.

Best Regards,
Daniel

Mar. 16, 2022 16:53:36 Kurt Aaholst ***@***.***>:

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few months.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still encounter this issue.

Thank you!
