### ISSUE TITLE
Missing Display/Sound icons / wrong bar symbols

### ISSUE THREAD

**Issue by MicPra** [kaaholst/android-squeezer#711]
Two minor issues:
If opening 'Display Settings - Boom/Transporter'  Settings -> Advanced -> Player Display, no Icons are displayed and under settings  

![Capture30](https://user-images.githubusercontent.com/81591642/120500040-d3d4ae00-c3c0-11eb-9efd-03838952be18.PNG)
'Min. Brightness (Auto)' and 'Sens. Brightness (Auto)' a bar with speakers symbols instead e.g. a sun symbol is shown.
![Capture31](https://user-images.githubusercontent.com/81591642/120500062-d931f880-c3c0-11eb-8f80-6a12c120c7ff.PNG)

 Similar: Settings -> Audio (Icons missing and 'Bass' and 'Treble' shows a bar with speaker symbols.
![Capture32](https://user-images.githubusercontent.com/81591642/120500220-f9fa4e00-c3c0-11eb-84e9-b213e315a60e.PNG)

**Comment by kaaholst** [comment]
This is fixed in 2.2.7 so closing this.

Thank you!
