### ISSUE TITLE
playlist can get out of sync

### ISSUE THREAD

**Issue by TheOriginalOrthonormal** [kaaholst/android-squeezer#713]
I have noticed with 2.2.6 and possibly the previous release that if a Squeezebox player is playing but Squeezer is not active for a while, when I reopen Squeezer it thinks that the currently playing track is what was playing when I switched focus away from Squeezer.  The playlist shown in the playlist view is what was shown when I switched away from Squeezer.  And when the currently playing track is moved forward or back, Squeezer steps forward or back through the stale playlist.  I can get it in sync by going to the process manager, closing Squeezer, and starting it up from scratch.

**Comment by theking2** [comment]
I just witnessed the same phenomenon [Screenshot_20220417-150848_Squeezer](https://user-images.githubusercontent.com/1612152/163715780-e6a9300d-1e2d-4437-b48c-246bd1ff5a23.jpg)

**Comment by kaaholst** [comment]
This is fixed from version 2.3.0, so closing this.

Thank you!
