### ISSUE TITLE
App does not connect to mysqueezebox.com

### ISSUE THREAD

**Issue by mrfishbsme** [kaaholst/android-squeezer#714]
App Version 2.2.6
Android 9
Lg stylo 5

Squeezebox is online and connects to mysqueezebox.com. works and plays.

App does not connect.
No option to enter login and password.
No players found.

Any suggestions?

**Comment by bvrulez** [comment]
The android app Squeezer is not supposed to connect to mysqueezebox.com, but to a Logitech Media Server that runs on your private network. Your Squeezebox would then also be connected to the local LMS and Squeezer will then show your box.

**Comment by kaaholst** [comment]
Squeezer does indeed connect to mysqueezebox.com :-)

Login and password are only requested the first time you connect. 

When connected to mysqueezebox.com you can select the players which are connected to same account on mysqueezebox.com. If there are no players connected to that account you will get a screen as the below example (but the Squeezer app has successfully connected to mysqueezebox.com).

If this is the case, you should check if your player(s) are actually connected to the same account mysqueezebox.com. This can be checked if you logon to mysqueezebox.com in a browser, or maybe you can see that on your player. If you want Squeezer to connect to another account on mysqueezebox.com, you need to delete Squeezer-app-data from your phone.

![billede](https://user-images.githubusercontent.com/428304/121715447-30ca1580-cadf-11eb-9183-35b0f3f09360.png)

**Comment by bvrulez** [comment]
Wow, it's really a swiss knive app!
