### ISSUE TITLE
Podcast description / More Menu

### ISSUE THREAD

**Issue by MicPra** [kaaholst/android-squeezer#716]
Podcast plugin in LMS 8.2 has its own Search/ More Menu - Squeezer shows whole description in one row without 'new line'
![Capture34](https://user-images.githubusercontent.com/81591642/124159956-047d3580-da9c-11eb-9717-08a9ad092fdd.PNG)

correct would be:
![Capture35](https://user-images.githubusercontent.com/81591642/124160011-165ed880-da9c-11eb-88b6-f4d1b72e0cf2.PNG)

**Comment by kaaholst** [comment]
I think this might be solved in version 2.3.2 with the context menu showing in a bottom sheet. Please retest

**Comment by MicPra** [comment]
Perfect - works now.... Thx and best regards
