### ISSUE TITLE
Volume change not working when Background Volume Control is enabled

### ISSUE THREAD

**Issue by chau-intl** [kaaholst/android-squeezer#721]
I have just updated to the latest 2.2.7-beta-1. 

When squeezer is running in the background and I have `Background Volume Control` enabled, I can no longer change call-, notification- or any other volume using the physical volume controls on the side of my phone - nothing happens when I press the buttons. As soon as I disable `Background Volume Control` my volume controls work again.

My OS is Xiaomi MIUI 12.0.5.

**Comment by kaaholst** [comment]
On my phone, when I press (MI UI 10) when I press the volume buttons the Squeezebox volume changes (via Squeezer) and the volume system popup is shown. I can then select a three-dot which opens a popup so I can control other volumes (call, notification and media). I've tested on several other devices and emulators, and it's all variations on this (but they all look different). Most works slightly better than MI UI 10, cause there's a specific slider for the Squeezer volume.

Maybe it's an issue of permissions on your phone?

**Comment by SamInPgh** [comment]
Also running 2.2.7-beta-1. The background volume control feature is not working for me at all. There is no difference in behavior with the option on or off. However, the equivalent setting for SqueezeCtrl does work. Android 7.1.1.

**Comment by kaaholst** [comment]
@SamInPgh 
This sounds like a different issue, since nothing is happening at all. The first thing to check is if Squeezer is connected to a LMS. Check if the ongoing notification is present. If Squeezer is connected, it may be that another app is getting the volume key events.

**Comment by SamInPgh** [comment]
Hey, Kurt. Sorry to hijack this issue but I am wondering if you saw my response to your comment to me awhile back on the following closed issue. I don't know how to contact you directly.   -Sam

https://github.com/kaaholst/android-squeezer/issues/710#issuecomment-856282354

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still encounter this issue.

Thank you!
