### ISSUE TITLE
Library View Selector Unresponsive

### ISSUE THREAD

**Issue by annomatik** [kaaholst/android-squeezer#723]
This is a crosspost of https://github.com/nikclayton/android-squeezer/issues/687 , as I don't know, what's the current github for that project.

Hi! There's something strange going on for me with selecting a library view.

When I press "All Library (Default)", nothing happens. My expectation would be, that there's a big dot in front of it, indicating, that it has been selected.

When I press "Ballroom" -> Use Ballroom, nothing happens either. Sometimes, when I press back afterwards, there's a dot in front of "Ballroom", sometimes, there isn't. My expectation would be, that after pressing "Use Ballroom", Squeezer would go back to the Library View overview screen and indicate with a dot, that Ballroom has been selected.

I am using Squeezer 2.2.7 on a Samsung S7.

![](https://user-images.githubusercontent.com/28311452/128571731-e81a3c8c-8d31-4ba4-9386-9c0482ac6bd2.jpg)

**Comment by kaaholst** [comment]
This is the proper place to report issues with the Squeezer app.

I'm not using Library Views myself, but indeed something seems to be wrong. I will investigate this, and see if I can figure something out.

If I do find a fix, would you be willing to help test it?

**Comment by annomatik** [comment]
Cool, thanks. Of course, I'll test it as soon as you are ready.

**Comment by kaaholst** [comment]
Please try this [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing). It has the same functionality as 2.2.7, which is the latest version, except for this fix.

Squeezer returns to the "My Music" menu after selecting the library view. When you re-enter the library view menu, the selected library shall have a dot in front of it.

**Comment by kaaholst** [comment]
Thanks for the feedback, I'm closing this issue.

You may continue to use this apk, it will automatically be updated when an new version is released. You can also revert to the version on Google Play, if you prefer to use an official version.

Thanks for the help testing this!
