### ISSUE TITLE
Feature Request - Treat VPN as WLAN

### ISSUE THREAD

**Issue by Dornteufel1** [kaaholst/android-squeezer#727]
If the device is connected to a VPN, it should not display the warning to enable WLAN and should just try to connect to the entered device

**Comment by kaaholst** [comment]
Please try to disable auto connect (in Squeezer select the three-dot-menu on the top right and select settings)

Hope this helps!

**Comment by Dornteufel1** [comment]
I am really sorry, that I opened an Issue for this. I could have found this out myself. 😓
