### ISSUE TITLE
Feature Request: FWD and Back assigned values

### ISSUE THREAD

**Issue by dworn** [kaaholst/android-squeezer#731]
I find jping forward and back in a track tricky, difficult to jump a precise number of seconds forward or back, would it be possible to set a user assigned period to jump forward or back, for example jump 10 seconds to skip the intro of a podcast  and the same for reverse ? This is implemented in such apps as Podcast Addict for reference.

**Comment by kaaholst** [comment]
Hi and thanks for the feedback.

I also think that jumping forward and backwards is tricky, happy to hear I'm not the only one.

For the next version of Squeezer I have added back and forward 10 seconds if you double tap on the left or right side of the album art respectively. You can try [this](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing) preview. I hope you like it.

**Comment by dworn** [comment]
Thanks for looking at this.
The fwd & back works as you described which is a big improvement. It seems
a bit tricky to get the icon overlay to appear (maybe it is me but it took
me awhile to realise you double tap then tap the icon overlay )

If the interval to jump can be configurable that would be a real winner.

Anyway thank you for taking the time to put in this feature as it will
enhance my experience of using Squeezer.

All the very best

**Comment by kaaholst** [comment]
I think I know what you mean. I have made a new suggestion which works like this:
Tap the album layout to bring up an overlay with two buttons to quickly jump 10 seconds backwards and forwards respectively. Each time the button is pressed Squeezer will skip 10 seconds backwards or the forwards, so if for example you want to skip 30 seconds, press the button three times. I have updated [the apk in the link](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing), you can try from there.

Now for the configurable period, I don't think I understand the use case, could you elaborate a bit further.

**Comment by dworn** [comment]
I will give the new APK a trial.
The use case I was explaining is as follows:
You already have the buttons as described to Ffwd and back that appear via
the album art. As you say they are set at 10 seconds per tap. But say I
wanted to have the Ffwd interval to be 20 seconds and the back set at 5
seconds ?
I could do that if the buttons could e assigned a interval time in the
settings (maybe default to 10 seconds but allow the user to change the
default).
Why would I want this feature. There are many podcasts etc that I skip the
introduction which is usually 10-15 seconds but I like to jump back 5
seconds if I have missed something. Thus I can start the podcast and with
single tap skip the introduction.
I hope this is a clearer example.

**Comment by kaaholst** [comment]
Thanks for the explanation, it makes sense. The link updated with the possibility to configure the jump. It will be in the next release of Squeezer.

**Comment by dworn** [comment]
Thank you for this. Happy to test the new version of required .

**Comment by kaaholst** [comment]
This is available in version 2.2.8 which is now on Google Play.

Please post back here if something is still missing, otherwise please close this.
