### ISSUE TITLE
crash while pressing 'More Info'

### ISSUE THREAD

**Issue by MicPra** [kaaholst/android-squeezer#735]
Squeezer 2.2.8-beta-1
Android 8.0.0

When pressing 'More Info' via 3 dot menu in Now Playing Screen, the App crashes

**Comment by kaaholst** [comment]
Thanks for the info. I will make a new beta with a fix for this.

**Comment by kaaholst** [comment]
This is fixed in 2.2.8-beta-2. Thanks for helping to fix this!
