### ISSUE TITLE
Crash when switching between portrait and landscape mode

### ISSUE THREAD

**Issue by SamInPgh** [kaaholst/android-squeezer#736]
Squeezer crashes when switching between portrait and landscape mode in many of the Settings menus. An easy way (for me) to recreate the problem is to select the "Settings->Alarm Clock" menu and then rotate my phone 90°. It also happens with some (but not all) of the other menus but I'm assuming they are all related. Fyi, I'm running v2.2.8-beta-1 on Android 7.1.1.

**Comment by SamInPgh** [comment]
Update: The problem is worse than I thought. It also crashes when changing orientation while browsing a list of albums or artists under My Music. This is very annoying.

**Comment by kaaholst** [comment]
Hi Sam,

I have made a new [version](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing) with a fix for this.

It will be available in the next beta (and release), as soon as we can get through Google approval .

Sorry for the inconvenience.

**Comment by SamInPgh** [comment]
The new version indeed fixed the problem, Kurt. Thanks for the quick response!

**Comment by kaaholst** [comment]
Ok, closing this. Thanks for the feedback.
