### ISSUE TITLE
Android lock screen-- controls appear but don't respond

### ISSUE THREAD

**Issue by blscorp** [kaaholst/android-squeezer#746]
Squeezer 2.2.7 on Android 10, Samsung Galaxy S9.

Can see the track info with play/pause and track advance/reverse buttons on lock screen, but they don't respond to touch, though phone's volume buttons work.

A bug?

**Comment by kaaholst** [comment]
I think it's a permission issue. Dependent on your device this may be: Android settings / Notifications / Apps.
On my phone I can control play/pause etc. when the device is locked.

**Comment by blscorp** [comment]
Thanks for response.  Notifications are already permitted in that setting, and the app shows up on the lock screen.  Maybe it's another general Android setting related to the lock screen, I'll report back if I figure it out

**Comment by blscorp** [comment]
Found it: had to turn off Music under FaceWidgets.  Now it works fine on lock screen.  Changing that setting also changed appearance of Squeezer on lock screen, I think Samsung was trying to show/control the app as it's own Music FaceWidget. Thanks again
