### ISSUE TITLE
Squeezer and Deezer hifi

### ISSUE THREAD

**Issue by plutoface** [kaaholst/android-squeezer#747]
I have Squeezer app, on my android phone. I subscribe to Deezer HIFI. I  use my phone as a squeezebox duet controller with the Squeezer app. When playing songs from Deezer, the bitrate on the phone only shows 320kbps,  although I subscribe to  Deezer HIFI   ... Any ideas why the kbps is shown so low..? Thanks/ Torben.

**Comment by kaaholst** [comment]
I think this is obsoleted by the new Deezer local plugin, which enables you to configure the playback quality server side. So closing this. Feel free to reopen if you disagree.
