### ISSUE TITLE
My android phone just updated and now Squeezer won't connect to my Squeezebox.

### ISSUE THREAD

**Issue by Jocar37** [kaaholst/android-squeezer#752]
My Sqeezebox is working. I'm listening to it now. But Squeezer won't connect and I don't know how to find the local server address. My Sqeezebox says neither LMS  nor the scanner are running. It gives me the opportunity to start LMS. but I don't know what that will do or how it might change my Sqeezebox.

**Comment by kaaholst** [comment]
Squeezer is supposed to find the local servers (LMS) automatically. If that doesn't work, it's possible to enter the server address manually.
May you can see on your Squeezebox to which server it is connected?
I'm not sure what you mean by "the opportunity to start LMS", could you elaborate?

**Comment by Jocar37** [comment]
I don't understand much about LMS and the Squeezebox.  I just went into the setting on the Squeezebox and under Squeezebox server it says "Niether Logitech Media Server nor the scanner are running."

Below that, it give me 2 options, "Start Logitech Media Server," and "Wipe and Rescan."  

Since it's not running, I would imagine there is no server, IP address, MAC address or anything.  

 

I don't understand what is or does, but my Squeezebox has been working for all other purposes. If it's already working, pulling in internet radio, Pandora, etc. , it would seem I don't need it.  Am I wrong?  or is there something it does for Tidal that isn't needed for other sources?  Maybe you can explain a little about what LMS does

**Comment by Jocar37** [comment]
Squeezer was connecting intermittently.  Now it won't connect at all.  I uninstalled and reinstalled it and it still won't run.  I know I am supposed to be able to enter the IP address manually, but when I finally found and entered the IP address for my Touch, the connection STILL  failed.  I don't get it.  My Squeezebox is running fine (except it can't do Tidal(?)), but Squeezer can't find it, even after reinstalling.  What else can I do?

**Comment by kaaholst** [comment]
Here is how Squeezer works:

Squeezer connect to an LMS which must be running and listening for connections on an IP-address. LMS also listens for broadcasts on the network to which it replies with it's address. This is how Squeezer finds the LMS'es on the local network. If this server lookup doesn't work for some reason, Squeezer gives the option to enter the address manually.

When Squeezer is connected to an LMS it communicates with LMS, which in turn communicates with the players (Squeezeboxes).

This means that Squeezer cannot work (nor connect), unless there is an LMS running on your network.

I don't have a touch, but I understand it has an embedded LMS,  so you don't have to run your own. It this is your setup then this embedded server has to be started in order for Squeezer to work.

I suggest you start LMS from your Squeezebox. Wipe and rescan is not necessary but won't matter unless you have your own music on the Squeezebox.

**Comment by Jocar37** [comment]
Well, I don't know what's supposed to happen, but what I'm experiencing doesn't match up.  My squeezbox setting said there was no LMS, so I chose the option that I thought would install and run it on my Squeezebox.  It didn't work at first because no storage device was connected (don't know why that would be necesary), so I attached a 1GB flashdrive, and it seemed to work.  But Squeezer still couldn't connect. So I went back in, found a new IP address for my Squeezebox and tried connecting Squeezer manually.  Before, it simply failed to connect.  When I put this new IP address in, it didn't show the connection failed.  Instead it said (still says) "no players are connected" even though my squeezebox is running!  And now it's stuck on the screen with that error message.  I can't even get Squeezer to back up to the prior screen and see if it will recognize the Squeezebox automatically.
I also don't see what the flash drive does, and wonder if removing it will hurt, help or be of no impact either way.
Now I don't know if this matters, but my Squeezebox i connected to our home network through an ethernet cable, not wifi.  My son set it up this way to maximize bandwidth for hi-def audio.

**Comment by Jocar37** [comment]
?

**Comment by kaaholst** [comment]
When Squeezer isn't connected it will display the connection screen. To connect, press the connect button. Squeezer will then try to connect. If this fails if will display "Connection failed". This is show in the first screenshot below.

The first thing Squeezer does when a connection is made, is to query LMS for the players (Squeezeboxes) which are connected to this LMS. Squeezer will use the player previously selected by user as the active player, or the first player returned by LMS is this is the first time you connect. 

Squeezer will then query LMS what this player can  do and display that on the home screen. This is shown on the second screenshot.

If no players are reported by LMS, Squeezer will display "No players are connected". This is shown in the third and final screenshot.

When Squeezer is connected to an LMS, you can disconnect using the 3-dot menu in the top right corner.

So it seems that what you are experiencing is what is expected. But you seem to have an issue with your LMS and/or Squeezebox setup. I am not able to help with that. I suggest you look for help on the [Squeezebox : Community : Forums](https://forums.slimdevices.com/). If you don't find the solution, you can create an issue, they are very helpful.

![image](https://user-images.githubusercontent.com/428304/155008053-6f1b995c-0339-4e30-af9f-6f7f0754d998.png)

![image](https://user-images.githubusercontent.com/428304/155008779-033286ff-7503-46ce-b4dc-061e775b41dc.png)

![image](https://user-images.githubusercontent.com/428304/155009142-9e047659-a35a-49e3-85b2-202899699c56.png)


So it seems that

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few months.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still encounter this issue.

Thank you!
