### ISSUE TITLE
Hardly connect LMS through WireGuard

### ISSUE THREAD

**Issue by ProteinPig** [kaaholst/android-squeezer#753]
I know expose port publicly is dangerous, hence I use wireguard on my phone instead. 

But I noticed that usually squeezer can't connect LMS. And the meantime lms on web works normally (such as material skin). Squeezer works perfectly on LAN.

**Comment by kaaholst** [comment]
I managed to get Wireguard working on my setup. I was then able to reproduce this issue when accessing Squeezer from the outside via mobile connection. This in turn enabled me to make a fix.

Please try this [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing).

You may continue to use this apk, it will automatically be updated when an new version is released. You can also revert to the version on Google Play, if you prefer to use an official version.

**Comment by ProteinPig** [comment]
THX, I have tried the new app, so far so good. Connection smooth like a butter. 
I will use this for several days to take a look at it. 

And is it means that I need update the apk manually if your update it? If I turn back to Google Play version the fix will lose?

**Comment by kaaholst** [comment]
Thanks for the feedback.

This fix is not in an official release of Squeezer yet. It will be included in the next version. If you uninstall this apk and install Squeezer from Google Play, you will loose this fix until it is officially released.

If you leave this apk on your device(s), it will be automatically updated as normal via Google Play when the next version of Squeezer is released.

**Comment by FitziCJ** [comment]
I'm glad that i did a Quick search into this github as i've had the same issue beeing connected with wireguard to my home network 
I can confirm that your fix is working fine. 

Thanks a lot for your good work
