### ISSUE TITLE
Feature request: add command to restart LMS server

### ISSUE THREAD

**Issue by sean-e** [kaaholst/android-squeezer#756]
I sometimes have to restart my Logitech Music Server.  Currently, I do this via telnet to the server and executing the `restartserver` command.  It would be helpful if Squeezer could execute the command via the addition of a restart command on either the `Settings | Advanced | Squeezebox Information` page or the `Settings | Advanced | Squeezebox Information | Logitech Media Server` page.

The `restartserver` command is documented in the Command Line Interface help page at `<your_server>/html/docs/help.html`.

**Comment by viertelb** [comment]
It should only be possible with username and password activated for LMS. Otherwise people would be able to randomply connect to other people's LMSs and restart the server. But I am not sure this is possible since we cannot test if a given password is the correct one, if there is no password set on the server.

**Comment by thingswelostinthefire** [comment]
To do that I use the "SvrPowerControl" plugin installed on LMS, it works flawlessly also through Squeezer.

It can be configured for activate/deactivate the LMS server in sync with the Squeezebox:
 - while turning on the Squeezebox the plugin can turn on the LMS machine from suspend
 - putting on suspend the LMS machine through the plugin it causes the Squeezebox to turn off after few seconds

**Comment by sean-e** [comment]
Thanks -- I wasn't aware of it:
https://github.com/gharris999/SrvrPowerCtrl

**Comment by kaaholst** [comment]
@thingswelostinthefire Thanks!
@sean-e I hope you're happy with this, so closing this.
If you still request the command to restart LMS, feel free to reopen.

**Comment by sean-e** [comment]
Implemented in commit https://github.com/kaaholst/android-squeezer/commit/431c24bbab67ddc35f8b6c644a7d1193057ef8c9

**Comment by kaaholst** [comment]
> Implemented in commit https://github.com/kaaholst/android-squeezer/commit/431c24bbab67ddc35f8b6c644a7d1193057ef8c9

Thanks, I completely forgot about this request😊
