### ISSUE TITLE
Data loss on double screen rotation

### ISSUE THREAD

**Issue by davirec** [kaaholst/android-squeezer#761]
Hi, this issue has a relation with #759.

We found failures similar in activities:

- ConnectActivity: lost form data and returned to the previous screen; lost form data, went back to the previous screen and lost fragment.

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159146389-d413e3b9-f472-48af-81c1-dac008ba183c.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159146390-9e496826-0f1a-49f6-b68a-d796e2b5c2f1.png" width=20% height=20%>
</figure>

</div> 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159146434-f07d4ea5-d99b-4a4f-b96a-1ce217450041.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159146430-3a769833-d4e1-4e7e-8e4c-d1a82b347835.png" width=20% height=20%>
</figure>

</div> 

- HomeActivity: lost the fragment, lost a list of elements.

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159146467-91c7b22d-6ca7-4a6d-95e1-e3a73fe82f1e.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159146460-b5bb6b6f-5fc3-4382-a052-08b92c6b45e0.png" width=20% height=20%>
</figure>

</div> 

- JiveItemListActivity: lost a lot of properties.

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159146486-a9e3f2ac-815b-4ad8-84f2-12d302ee373b.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159146489-466bd0a5-7fac-4fa4-802c-c16d065a5fe5.png" width=20% height=20%>
</figure>

</div> 

Note:

- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few months.

Thank you!
