### ISSUE TITLE
Request : statistics

### ISSUE THREAD

**Issue by Tedd22** [kaaholst/android-squeezer#763]
It would be very appreciated to be able to consult the statistics of the library: number of songs, number of artists, number of albums

**Comment by kaaholst** [comment]
Please select Settings / Advanced / Squeezebox Information / Library Statistics.
Long Press to put shortcut on Home Screen.

Hope this helps!

**Comment by Tedd22** [comment]
I've been using my squeezebox touch for more than 10 years and I've never discovered this section before... Thanks for the tip and eternal thanks for the great app !
