### ISSUE TITLE
Volume control not working at all?

### ISSUE THREAD

**Issue by StewLG** [kaaholst/android-squeezer#771]
I have just started using Squeezer for the first time, although I've run LMS for many years and done development on it and written plug-ins, etc.

Volume control doesn't seem to be working at all for me. Not up, not down - not even mute. It doesn't work for a Squeezebox Radio, or for a Squeezebox controlling volume via IR Blaster to a receiver. 

I do have full playlist and player controls, artwork, etc. so that much seems fine.

Am I missing something?

**Comment by kaaholst** [comment]
I'm sorry, I don't know why volume control would not work for you. Squeezer does not do anything special for volume, and there should not be any specific requirements for volume control to work.

If you are familiar with the technical infrastructure of LMS, Squeezer uses the "mixer volume" and "mixer muting" CLI commands to control the volume, which we send via the CometD protocol. This is the same method we use for "play", "pause", "playlist shuffle", ... commands.

I have two Squeezebox Radios, and I can confirm volume control works for them. I'm not familiar with the IR blaster.

Does volume control work from the controls on the radio itself, or maybe it's something with your LMS setup.

To verify that Squeezer sends volume control to LMS, in the LMS web interface you can select Settings/Advanced/Logging, and raise the log level of "network.cometd" to Debug. Then via Information/Logitech Media Server Log File, inspect the log file for "mixer volume" entries.

**Comment by StewLG** [comment]
I restarted my phone, and it works now.

The only thing I can think of is I mis-typed the URL for my server into the app originally. Perhaps part of the app cached the bad value and was trying to call for volume changes on the bad URL, while everything else was using the correct URL. If that suggestion indicates an obvious fix, great, otherwise don't worry about it.

**Comment by kaaholst** [comment]
Thanks for the update, I'm happy you got it working.

I don't know the reason for this, Squeezer uses the same connection for all commands to LMS (except for download of artwork).
