### ISSUE TITLE
Space for 'Player names' in 'Now playing' screen

### ISSUE THREAD

**Issue by MicPra** [kaaholst/android-squeezer#774]
Could you give the player names in the Now playing screen a bit more space. My player names a bit longer... the start screen fits perfect...

![Screenshot_20221116_215015_Squeezer](https://user-images.githubusercontent.com/81591642/202292135-1bb684ef-654d-4e2d-8436-c46c6954a87d.jpg)
![Screenshot_20221116_215007_Squeezer](https://user-images.githubusercontent.com/81591642/202292177-7a90b295-a3c0-49de-859e-a3d834fa8e63.jpg)

**Comment by kaaholst** [comment]
The player drop down will now use the entire screen width for small displays. Also, slightly more space for the selected player.

This is available from version 2.3.2, so closing this. Thank you!
