### ISSUE TITLE
Display Full Path of Music file

### ISSUE THREAD

**Issue by cathcam** [kaaholst/android-squeezer#775]
All my music is stored on a NAS, remoted linked into LMS on a WIN10 PC. They are stored in 
\nas-name\media\music\artist\album\

Using Squeezer if I use the Now playing view, press the threedots file menu on the lower right, the first menu appears in white text on a dark theme; from there I choose "More Info" the second menu shows up in a faint gray in dark theme.

The location field on the second menu is the same for all my music. It says Location:\\nas-name\media

I'm typically interested in to locate a file that needs updated tags, album artwork, etc. or in the case of the some 2,000 vinyl albums I've ripped, rerecording.

1. Please change the color of the 2nd menu text to the same way it's defined for the first menu.
2. Provide a mechanism to display the entire path and name of an individual music file ie. "\\nas-name\media\music\David Bowie\Wild Is The Wind.mp3"

Also, if possible, make the file path+name able to be copied so it can be paste into notes/emails/to-do lists.

Thank you for considering these requests.

++Mark. 
https://ctproduced.com

**Comment by kaaholst** [comment]
The context menu now displays in a bottom sheet. This means more space available for items. Items which cannot be selected are displayed in a lighter shade. This is as before, however the lighter shade is made more readable.

This is available from version 2.3.1, so closing this. Thank you!

**Comment by cathcam** [comment]
This is an awesome improvement. Thanks so much. 


⁣++Mark.
__________
https://ctproduced.com
https://markcathcart.com/about/​
