### ISSUE TITLE
Music does not stop when telephone rings (android)

### ISSUE THREAD

**Issue by willemstegenga** [kaaholst/android-squeezer#777]
The Music does not stop when telephone rings (android), it used to work perfect but not after the last update of Squeezer

**Comment by kaaholst** [comment]
Please tell me which Android version you have, then I'll see what I can do

**Comment by willemstegenga** [comment]
Samsung A53

Thanks in advance

Greetings
Willem

Op wo 7 dec. 2022 21:58 schreef Kurt Aaholst ***@***.***>:

**Comment by willemstegenga** [comment]
Version 13

Op wo 7 dec. 2022 21:58 schreef Kurt Aaholst ***@***.***>:

**Comment by kaaholst** [comment]
I found a bug, I will send out a new version as soon as I can.

If you would like to help test this, you can do with this [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing). It will be updated automatically when the new version is released.

Thanks for reporting this!

**Comment by willemstegenga** [comment]
It works very well.  Thanks.


Op ma 12 dec. 2022 18:56 schreef Kurt Aaholst ***@***.***>:

**Comment by willemstegenga** [comment]
It does work, but unfortunately not all the time. It depends which squeezer
screen is on.

Met vriendelijke groet
Willem Stegenga
06-51479041


Op ma 12 dec. 2022 om 18:56 schreef Kurt Aaholst ***@***.***>:

**Comment by kaaholst** [comment]
It's supposed to work from every screen. If possible, can you elaborate which screen it's not working.

For reference, here's how it should work:

- When Squeezer is connected to an LMS, we listen for call state changes.
  (That is when the Squeezer Notification is shown)
- When we receive notification that a call is active, we perform the action defined in settings (pause music, mute music or nothing).

This means that it should work regardless which screen is showing, and even if another app is showing or the phone is sleeping.

**Comment by kaaholst** [comment]
It's supposed to work from every screen. If possible, can you elaborate which screen it's not working.

For reference, here's how it should work:

- When Squeezer is connected to an LMS, we listen for call state changes.
  (That is when the Squeezer Notification is shown)
- When we receive notification that a call is active, we perform the action defined in settings (pause music, mute music or nothing).

This means that it should work regardless which screen is showing, and even if another app is showing or the phone is sleeping.

**Comment by kaaholst** [comment]
This is fixed from version 2.3.1, so closing this. Thank you!

**Comment by willemstegenga** [comment]
THANK YOU

Op ma 16 jan. 2023 22:40 schreef Kurt Aaholst ***@***.***>:
