### ISSUE TITLE
Thumbnails messed up

### ISSUE THREAD

**Issue by nilskp** [kaaholst/android-squeezer#784]
This is a screenshot from the LMS web interface:
![Screenshot_20230120-083902](https://user-images.githubusercontent.com/74843/213726075-05fee5fb-72f6-47b0-910b-6c7b556bb86b.png)

This is from Squeezer:
![Screenshot_20230120-083819](https://user-images.githubusercontent.com/74843/213726406-3de458eb-f1f5-4502-80b3-4533dcf0cb7f.png)
As can be seen, the playlist is identical, but the thumbnails are confused, showing from different albums in the playlist.

Squeezer: 2.3.1

**Comment by rkversion** [comment]
+1
I also see this very often. 
Scrolling the playlist up/down refreshes the artwork and right covers show up.

**Comment by Tillerman77** [comment]
+2, I also am seeing this most of the time.

**Comment by kaaholst** [comment]
This should be fixed from version 2.3.7, closing this. If you still experience the issue, feel free to reopen. Thank you!
