### ISSUE TITLE
Feature Request: Bitrate \ Sampling Rate like Web

### ISSUE THREAD

**Issue by grendelrt** [kaaholst/android-squeezer#785]
Any way to add the bitrate and sampling rate to the now playing screen when its maximized like the web page version?
![Screenshot 2023-02-10 183441](https://user-images.githubusercontent.com/42378882/218221942-e8d251f8-295f-4bf2-8ab1-c648b2c1bde5.png)

**Comment by kaaholst** [comment]
That's a good idea, thanks for the suggestion.
We now have access to this information from LMS, it will be available in the next version.
It looks like this:
<img src="https://github.com/user-attachments/assets/361bbf55-e30f-417a-a578-aa10b1c5dd53" alt="drawing" width="250"/>
Suggestions or comments are welcome!

**Comment by grendelrt** [comment]
> That's a good idea, thanks for the suggestion. We now have access to this information from LMS, it will be available in the next version. It looks like this: <img alt="drawing" width="250" src="https://private-user-images.githubusercontent.com/428304/349260699-361bbf55-e30f-417a-a578-aa10b1c5dd53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNjU4MTMsIm5iZiI6MTcyMTE2NTUxMywicGF0aCI6Ii80MjgzMDQvMzQ5MjYwNjk5LTM2MWJiZjU1LWUzMGYtNDE3YS1hNTc4LWFhMTBiMWM1ZGQ1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQyMTMxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzkyZjVmMjI1NDg0M2ZhOTQwYzBlODI4ZDE2M2E5ZjBkMmJmNzY1MzU2ZDQ4NDEwNjk5OTQ0ZGUxOTIwODhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zg3-9K7m2uIvBwVP1eSqJEd_N_rR6fyBo1CqZGtWZfM"> Suggestions or comments are welcome!

Thats awesome, thanks for looking into it!

**Comment by kaaholst** [comment]
This is available from version 2.3.7, so closing this. Thank you!
