### ISSUE TITLE
Not able to play/play next albums or songs

### ISSUE THREAD

**Issue by SimonMadle** [kaaholst/android-squeezer#788]
Just upgraded to 2.3.2
Any album or song cannot play it by selecting three dots drop down, just displays album cover
Random mix will play things

**Comment by kaaholst** [comment]
Not sure if I understand. Below is what get when I select the 3-dot button on an album or a song. When I select play, it starts playing.
![billede](https://user-images.githubusercontent.com/428304/225696464-79111f43-7f26-4859-a9be-41c4ef2cb314.png)

**Comment by SimonMadle** [comment]
![Screenshot_20230316-171618_Squeezer](https://user-images.githubusercontent.com/128047764/225702660-7653161a-1983-4ada-a96d-5ff8c8ac8523.jpg)
Mine looks like this when I press the three dots on my Galaxy Tab A

**Comment by kaaholst** [comment]
This is fixed in version 2.3.5, so closing this
