### ISSUE TITLE
Pause/FF controls missing from lock screen on Pixel 7

### ISSUE THREAD

**Issue by climategadgets** [kaaholst/android-squeezer#794]
### Expected behavior

Squeezer displays the current track, album artwork, and Pause/Play and FF controls on the lock screen

### Actual Behavior

Squeezer displays the current track, album artwork, small image with the sign "Other devi..." (yes, literally that) in the top right corner of the album artwork, and nothing else. No manipulations with the lock screen allow to show the controls.

### Hardware and Operating System

Google Pixel 7
Android 13
Security Update April 5, 2023
Google Play System Update October 1, 2022
Build Number TQ2A.230405.003.E1

PS: This was observed throughout all the update history starting a few weeks ago. It is also not observed on a Pixel 3a with Android 12, may be Android 13 specific.

**Comment by kaaholst** [comment]
Unfortunately, music controls on the lock screen or notifications doesn't work on Android 13.

This is tracked in #781 so closing this

Thanks for the feedback.
