### ISSUE TITLE
Feature request: move fwd/back in track

### ISSUE THREAD

**Issue by time4tea** [kaaholst/android-squeezer#795]
Firstly, thanks for a lovely bit of software. My family use it on our 4 squeezeboxes.

When listening to long tracks, navigation is quite difficult - for example a long mix, or a programme on iplayer.

In this case, grabbing the scrollbar and moving it can move +/- 10mins, and it is quite stressful, and move to end is not right either.

It would be amazing if a "move in track" back/fwd button or capability could be added to move 1/2/5/10 or something mins fwd or back in the current track. I was sort of thinking like a ffwd/rwd button between the play and next/prev buttons, but of course the capability could be implemented in many ways.

For long radio programmes and long mp3 files, this would be an amazing capability. Unless of course it already exists and I just never saw it, in which case, sorry for this, and please how can I find it.

Thanks for your time!

James

**Comment by kaaholst** [comment]
You can try to tap the album art. This will bring up back and fwd buttons. By default, they will move 10 seconds back or fwd. You can press the settings button between the back and fwd buttons, to change how much to move back and forward.
