### ISSUE TITLE
Can't find the playlist any more (2.3.3)

### ISSUE THREAD

**Issue by guiv42** [kaaholst/android-squeezer#801]
First of all: thank you for this app.
I might have missed something obvious, if so please just tell me.

I upgraded from 2.3.2 to 2.3.3, and I can't find any more how to display the playlist. The control I used previously has disappeared to display a wider volume control. See the following screenshots of 2.3.2 (where I highlighted the control) then 2.3.3 (where I can't find it any more). Is there another way to access the playlist?
![2 3 2](https://github.com/kaaholst/android-squeezer/assets/129443524/b28d1797-38e9-42f6-a50a-ad9f6cf1d164)
![2 3 3](https://github.com/kaaholst/android-squeezer/assets/129443524/8fd48547-9361-4c01-851b-1f2ccd024b67)

My config: Samsung A41, Android 12, versions of android-squeezer downloaded from F-droid.

**Comment by kaaholst** [comment]
Hi,

You find the button for the playlist at the top right, next to the three dots.
![billede](https://github.com/kaaholst/android-squeezer/assets/428304/438c1a94-0887-4d7b-a5f5-e9abedd284d8)
It is available anywhere, not only from the now playing screen.

Hope this helps, and thanks for the detailed description.

**Comment by guiv42** [comment]
Obviously I had missed something...
Thank you for that fast answer!
