### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by NE3055** [kaaholst/android-squeezer#804]
I've been using Squeezer for years now. But squeezer hasn't connected to my phone for months. On my tablet, squeezer only connects after several attempts. Often the home screen is displayed for a moment, but then goes back to disconect.

Phone and Tablet has MIUI 14 (based on Android 13)

My old Android 11 phone connects without any problems on the first try.
So it can't actually be my WiFi or router.

**Comment by kaaholst** [comment]
I'm using MIUI 14 / Android 13 without any issues.
I suggest you delete app-data on the MIUI devices. Long press the app-icon, select app-info, storage, clear data and clear all data. Hope this helps.

**Comment by kaaholst** [comment]
Hmm ... there may be issues with MIUI. However, there are other users with Redmi Note 11S, and since you are able to connect from another device, I think it should work. You could also try to install and reinstall Squeezer on the failing devices.

**Comment by NE3055** [comment]
I've already tried uninstalling and reinstalling it.
Unfortunately, manually installing the apk v2.3.1 or v2.3.2 is also unsuccessful.

**Comment by kaaholst** [comment]
Maybe a stupid question, but did you try to completely turn the devices off and on?
How did you get the 2.3.1 and 2.3.2 apk?

**Comment by kaaholst** [comment]
And please also verify, that the device which doesn't connect at all actually is on (the correct) WiFi

**Comment by NE3055** [comment]
Yes, I've already tried the complete restart.
I downloaded the apk from apkpure.com. but doesn't last long and updated to 2.3.3.

I just see the max2play server is on 5g wifi and my redmi note 11s is on 2.4g wifi. but my old android 11 device is also on 2.4g wifi and it works perfectly. 
But it's a good approach with 2.4g vs. 5g
I'll see what I can do in my mesh wifi.

**Comment by NE3055** [comment]
Since version 2.3.5 everything is working as usual again. 
All devices work.
Thanks a lot!
