### ISSUE TITLE
Problème de parasites audio

### ISSUE THREAD

**Issue by gebeGbx** [kaaholst/android-squeezer#809]
[Voix 001_sd.zip](https://github.com/kaaholst/android-squeezer/files/13848578/Voix.001_sd.zip)

Au lancement de la publicité je reçois un bruit parasite très fort (voir le fichier audio) et  ceci uniquement pendant la publicité

d'avance merci

**Comment by kaaholst** [comment]
This issue is caused by the server and/or the audio source. Squeezer does not play audio on its own, it only sends commands for the server to play the selected audio.
