### ISSUE TITLE
Feature request: automatically open 'my music' when using search

### ISSUE THREAD

**Issue by Vansloneker** [kaaholst/android-squeezer#815]
When using search, I have to first expand 'my music' to go to the results.
Since after search I always go to 'my music' (what else...) I'd like to have 'my music' opened automatically with the search results if possible.

Thank you so much for maintaining the app!
Rick Vansloneker

![WhatsApp Image 2024-03-17 at 23 46 43](https://github.com/kaaholst/android-squeezer/assets/104866495/3a2da76a-62fb-489c-829e-a7d99e8e4c2e)
![WhatsApp Image 2024-03-17 at 23 46 44](https://github.com/kaaholst/android-squeezer/assets/104866495/8b1571fe-40f4-4da8-94e7-280982c7ec9e)

**Comment by kaaholst** [comment]
When you select search from the top bar, Squeezer currently executes the search found in the Home screen. I believe LMS calls this global search. If you instead select My Music and then select search, LMS will return search results for My Music only. These results will be initially expanded.

So we can create an option to choose whether search from the top bar performs global search or My Music search. What do you think?

Thanks for the feedback!

**Comment by Vansloneker** [comment]
Thanks for the quick reply!
I actually only use the top bar search when playing and a random track comes to my mind.
The option you suggest will probably be satisfying for all users.

**Comment by kaaholst** [comment]
This is available from version 2.3.6, so closing this. Thank you!

**Comment by Vansloneker** [comment]
Thank you so much for adding this feature. It is done perfectly.
