### ISSUE TITLE
Delete player group

### ISSUE THREAD

**Issue by HankDee** [kaaholst/android-squeezer#817]
![Screenshot_20240407-141915_Squeezer](https://github.com/kaaholst/android-squeezer/assets/133971347/07c8e61e-3199-4ff2-9c51-3a7f657b8e73)
Have a new setup using ChromecastBridge, works fine with a SB3 and two Chromecasts. In Squeezer I by mistake grouped two players and now I would like to delete the group... Can't find a way to do it.

**Comment by kaaholst** [comment]
From the players list you are showing, select the three-dot menu to the right of any of the grouped players. Then select synchronize, and no synchronization in the popup.
Hope this helps!
