### ISSUE TITLE
Feature request: Move current play to new player

### ISSUE THREAD

**Issue by NohWayJose** [kaaholst/android-squeezer#821]
When I'm listening to a rewound BBC Sounds program and I'm moving to another room, it would be great (a lot easier) to have a menu option "move to...". Then, if selected shows radio-button list of available players, for user to select. 

BBC Sounds probably isn't the only use case but it's the one I have the most.

Current and decidedly time consuming alternative is to memorize progress time,  go to new player, then navigate back to program and FF to correct time.

**Comment by NohWayJose** [comment]
It's sort of a cousin to 'synchronize'

**Comment by kaaholst** [comment]
This is certainly a valid use case and a good idea, your request is noted. We have similar requests from other users. There's a new version being released soon, and this change unfortunately won't make into that. So this will come in a later version.

**Comment by NohWayJose** [comment]
If you want to make it really snazzy, it would be great to register a device (phone or Apple Tag, etc) and use the location (bluetooth?) of that to have your current stream follow you from place to place. I realise this is a different level of ask but thought I'd post it anyway ;P

**Comment by kaaholst** [comment]
This will be available in the next version. I added the option to the dropdown where you change the player Squeezer is controlling. You can choose to continue playing on the player you switch to. It looks like this:
<img src="https://github.com/user-attachments/assets/d12a3ffe-9f2c-4422-8880-5f9fd835ed4a" alt="drawing" width="250"/>

If you would like to help test this, you use this [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing).

When you are done testing, you may continue to use this apk, it will automatically be updated when a new version is released.

**Comment by kaaholst** [comment]
This is available in 2.3.7 so closing this.
Regarding the request for having the current playlist (or stream) follow via a registered tag on a device, please raise that in a separate issue, if you are still interested.
