### ISSUE TITLE
Lyrion Media Server 

### ISSUE THREAD

**Issue by theking2** [kaaholst/android-squeezer#831]
Time to update the README.md to name it Lyrion Media Server

**Comment by Daksol** [comment]
> Time to update the README.md to name it Lyrion Media Server 

To be precise it is now "Lyrion Music Server".

**Comment by theking2** [comment]
I do stand corrected.

**Comment by kaaholst** [comment]
Done!
While at it, I changed it in all places. Changes are already visible at GitHub. Other changes are visible when it is released on Google Play.
Thanks for the feedback!
