### ISSUE TITLE
Alarm: weekdays cannot be deselected

### ISSUE THREAD

**Issue by homeassistanthomegear** [kaaholst/android-squeezer#834]
If you create or modify an alarm, you can select weekdays but not deselect them anymore.
Squeezer 2.3.6 with Lyrion Music Server Version: 9.0.0 - 1723965286 @ Mon Aug 19 02:29:16 CEST

**Comment by kaaholst** [comment]
This will be fixed in the next version. Thanks for the feedback!

**Comment by kaaholst** [comment]
This is fixed in 2.3.7, closing this.
