### ISSUE TITLE
White text in Player picker menu in light theme

### ISSUE THREAD

**Issue by cucko** [kaaholst/android-squeezer#838]
![Screenshot_2024-11-08-16-56-47-771_uk org ngo squeezer](https://github.com/user-attachments/assets/5fba9d19-ebb4-49fd-b935-a4a16515393c)

**Comment by kaaholst** [comment]
Confirmed, thanks for the feedback. I will look into asap.

**Comment by kaaholst** [comment]
This will be fixed in 2.3.7-beta-3.

**Comment by kaaholst** [comment]
This is fixed in 2.3.7 which is now available in Google Play, closing this. Thanks for the help in sorting this out.
